### ISSUE TITLE
Option to not separate audio and video.

### ISSUE THREAD

**Issue by douglasg14b** [bloomtom/DEnc#3]
For MPEG-DASH, audio and video need not be separated, they can both be in the same segment.

Is there an option to disable this? If not, can it be added?

**Comment by bloomtom** [comment]
When you say audio and video in the same segment, do you mean a multiplexed output stream?

MPEG-DASH does support multiplexed audio and video, but player support for more than one channel of audio is sparse, and by sparse I mean browsers don't support it. So if you have multiple languages, commentary, or other audio tracks, you will only get one upon playback in a browser. Demultiplexed streams are encouraged when possible since they offer more flexibility with the only downside being you have more files. The physical storage increase is typically negligible though.

When I designed DEnc I implemented only demultiplexed encoding. Supporting demultiplexed output is more complex than supporting multiplexed output, but supporting both is even more complex of course. At the time I did consider if having a multiplexed option would be beneficial, but I could not come up with a scenario where this was needed. Is it for your use? If so, what is your application? I am very curious!

**Comment by douglasg14b** [comment]
In our case a multiplexed stream is not required, it would just make the storage and access simpler.

Consider accessing the Video & Audio less directly than by the file names. The client would request segments not by name, but by Id, which the server then retrieves from say AWS S3. This does of course make it marginally more complicated to differentiate between requests for a video segment and requests for an audio segment.

I can make this work either way, but having them as a single file simplifies the DB models and the access mechanisms, and these files will only have a single audio channel.

**Comment by bloomtom** [comment]
I've thought about this for a long time, but I just can't reason out a way to do it without adding a lot of unnecessary complexity just to simplify things somewhat in an edge use case. So I'm sorry to say, I'm going to close this as Won't Implement.
